[package]
name = "_06_network"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
bytes = "1.9.0"
futures = "0.3.31"
libp2p = { version = "0.39",  features = ["tcp-tokio"] }
rocket = { version = "0.5.1", features = ["json"] }
tokio = "1.42.0"
tokio-util = "0.7.13"
